#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSearching
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_accounts")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertfileContaner(fileContaner instance);
    partial void UpdatefileContaner(fileContaner instance);
    partial void DeletefileContaner(fileContaner instance);
    partial void InsertFiles(Files instance);
    partial void UpdateFiles(Files instance);
    partial void DeleteFiles(Files instance);
    partial void InsertPredmetDB(PredmetDB instance);
    partial void UpdatePredmetDB(PredmetDB instance);
    partial void DeletePredmetDB(PredmetDB instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    partial void InsertuserInRoles(userInRoles instance);
    partial void UpdateuserInRoles(userInRoles instance);
    partial void DeleteuserInRoles(userInRoles instance);
    partial void Insertwebpages_Membership(webpages_Membership instance);
    partial void Updatewebpages_Membership(webpages_Membership instance);
    partial void Deletewebpages_Membership(webpages_Membership instance);
    partial void Insertwebpages_OAuthMembership(webpages_OAuthMembership instance);
    partial void Updatewebpages_OAuthMembership(webpages_OAuthMembership instance);
    partial void Deletewebpages_OAuthMembership(webpages_OAuthMembership instance);
    partial void Insertwebpages_Roles(webpages_Roles instance);
    partial void Updatewebpages_Roles(webpages_Roles instance);
    partial void Deletewebpages_Roles(webpages_Roles instance);
    partial void Insertwebpages_UsersInRoles(webpages_UsersInRoles instance);
    partial void Updatewebpages_UsersInRoles(webpages_UsersInRoles instance);
    partial void Deletewebpages_UsersInRoles(webpages_UsersInRoles instance);
    partial void InsertUserProfile(UserProfile instance);
    partial void UpdateUserProfile(UserProfile instance);
    partial void DeleteUserProfile(UserProfile instance);
    partial void InsertPredmetForUser(PredmetForUser instance);
    partial void UpdatePredmetForUser(PredmetForUser instance);
    partial void DeletePredmetForUser(PredmetForUser instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_accountsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fileContaner> fileContaner
		{
			get
			{
				return this.GetTable<fileContaner>();
			}
		}
		
		public System.Data.Linq.Table<Files> Files
		{
			get
			{
				return this.GetTable<Files>();
			}
		}
		
		public System.Data.Linq.Table<PredmetDB> PredmetDB
		{
			get
			{
				return this.GetTable<PredmetDB>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<Table> Table
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
		
		public System.Data.Linq.Table<userInRoles> userInRoles
		{
			get
			{
				return this.GetTable<userInRoles>();
			}
		}
		
		public System.Data.Linq.Table<webpages_Membership> webpages_Membership
		{
			get
			{
				return this.GetTable<webpages_Membership>();
			}
		}
		
		public System.Data.Linq.Table<webpages_OAuthMembership> webpages_OAuthMembership
		{
			get
			{
				return this.GetTable<webpages_OAuthMembership>();
			}
		}
		
		public System.Data.Linq.Table<webpages_Roles> webpages_Roles
		{
			get
			{
				return this.GetTable<webpages_Roles>();
			}
		}
		
		public System.Data.Linq.Table<webpages_UsersInRoles> webpages_UsersInRoles
		{
			get
			{
				return this.GetTable<webpages_UsersInRoles>();
			}
		}
		
		public System.Data.Linq.Table<UserProfile> UserProfile
		{
			get
			{
				return this.GetTable<UserProfile>();
			}
		}
		
		public System.Data.Linq.Table<PredmetForUser> PredmetForUser
		{
			get
			{
				return this.GetTable<PredmetForUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fileContaner")]
	public partial class fileContaner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _whoUserId;
		
		private System.Nullable<System.DateTime> _data;
		
		private System.Nullable<int> _programId;
		
		private System.Nullable<int> _scanId;
		
		private System.Nullable<int> _docsId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnwhoUserIdChanging(System.Nullable<int> value);
    partial void OnwhoUserIdChanged();
    partial void OndataChanging(System.Nullable<System.DateTime> value);
    partial void OndataChanged();
    partial void OnprogramIdChanging(System.Nullable<int> value);
    partial void OnprogramIdChanged();
    partial void OnscanIdChanging(System.Nullable<int> value);
    partial void OnscanIdChanged();
    partial void OndocsIdChanging(System.Nullable<int> value);
    partial void OndocsIdChanged();
    #endregion
		
		public fileContaner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whoUserId", DbType="Int")]
		public System.Nullable<int> whoUserId
		{
			get
			{
				return this._whoUserId;
			}
			set
			{
				if ((this._whoUserId != value))
				{
					this.OnwhoUserIdChanging(value);
					this.SendPropertyChanging();
					this._whoUserId = value;
					this.SendPropertyChanged("whoUserId");
					this.OnwhoUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime")]
		public System.Nullable<System.DateTime> data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programId", DbType="Int")]
		public System.Nullable<int> programId
		{
			get
			{
				return this._programId;
			}
			set
			{
				if ((this._programId != value))
				{
					this.OnprogramIdChanging(value);
					this.SendPropertyChanging();
					this._programId = value;
					this.SendPropertyChanged("programId");
					this.OnprogramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scanId", DbType="Int")]
		public System.Nullable<int> scanId
		{
			get
			{
				return this._scanId;
			}
			set
			{
				if ((this._scanId != value))
				{
					this.OnscanIdChanging(value);
					this.SendPropertyChanging();
					this._scanId = value;
					this.SendPropertyChanged("scanId");
					this.OnscanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docsId", DbType="Int")]
		public System.Nullable<int> docsId
		{
			get
			{
				return this._docsId;
			}
			set
			{
				if ((this._docsId != value))
				{
					this.OndocsIdChanging(value);
					this.SendPropertyChanging();
					this._docsId = value;
					this.SendPropertyChanged("docsId");
					this.OndocsIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Files")]
	public partial class Files : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Data.Linq.Binary _FileData;
		
		private string _MimeType;
		
		private string _Name;
		
		private string _AboutFile;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFileDataChanging(System.Data.Linq.Binary value);
    partial void OnFileDataChanged();
    partial void OnMimeTypeChanging(string value);
    partial void OnMimeTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAboutFileChanging(string value);
    partial void OnAboutFileChanged();
    #endregion
		
		public Files()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileData", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileData
		{
			get
			{
				return this._FileData;
			}
			set
			{
				if ((this._FileData != value))
				{
					this.OnFileDataChanging(value);
					this.SendPropertyChanging();
					this._FileData = value;
					this.SendPropertyChanged("FileData");
					this.OnFileDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MimeType", DbType="VarChar(151)")]
		public string MimeType
		{
			get
			{
				return this._MimeType;
			}
			set
			{
				if ((this._MimeType != value))
				{
					this.OnMimeTypeChanging(value);
					this.SendPropertyChanging();
					this._MimeType = value;
					this.SendPropertyChanged("MimeType");
					this.OnMimeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(151)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutFile", DbType="VarChar(MAX)")]
		public string AboutFile
		{
			get
			{
				return this._AboutFile;
			}
			set
			{
				if ((this._AboutFile != value))
				{
					this.OnAboutFileChanging(value);
					this.SendPropertyChanging();
					this._AboutFile = value;
					this.SendPropertyChanged("AboutFile");
					this.OnAboutFileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PredmetDB")]
	public partial class PredmetDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Disciplina;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDisciplinaChanging(string value);
    partial void OnDisciplinaChanged();
    #endregion
		
		public PredmetDB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disciplina", DbType="NVarChar(50)")]
		public string Disciplina
		{
			get
			{
				return this._Disciplina;
			}
			set
			{
				if ((this._Disciplina != value))
				{
					this.OnDisciplinaChanging(value);
					this.SendPropertyChanging();
					this._Disciplina = value;
					this.SendPropertyChanged("Disciplina");
					this.OnDisciplinaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleId;
		
		private string _RoleName;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public Roles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _whoUserId;
		
		private System.Nullable<System.DateTime> _data;
		
		private System.Data.Linq.Binary _program;
		
		private System.Data.Linq.Binary _scan;
		
		private System.Data.Linq.Binary _docs;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnwhoUserIdChanging(System.Nullable<int> value);
    partial void OnwhoUserIdChanged();
    partial void OndataChanging(System.Nullable<System.DateTime> value);
    partial void OndataChanged();
    partial void OnprogramChanging(System.Data.Linq.Binary value);
    partial void OnprogramChanged();
    partial void OnscanChanging(System.Data.Linq.Binary value);
    partial void OnscanChanged();
    partial void OndocsChanging(System.Data.Linq.Binary value);
    partial void OndocsChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whoUserId", DbType="Int")]
		public System.Nullable<int> whoUserId
		{
			get
			{
				return this._whoUserId;
			}
			set
			{
				if ((this._whoUserId != value))
				{
					this.OnwhoUserIdChanging(value);
					this.SendPropertyChanging();
					this._whoUserId = value;
					this.SendPropertyChanged("whoUserId");
					this.OnwhoUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime")]
		public System.Nullable<System.DateTime> data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_program", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary program
		{
			get
			{
				return this._program;
			}
			set
			{
				if ((this._program != value))
				{
					this.OnprogramChanging(value);
					this.SendPropertyChanging();
					this._program = value;
					this.SendPropertyChanged("program");
					this.OnprogramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scan", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary scan
		{
			get
			{
				return this._scan;
			}
			set
			{
				if ((this._scan != value))
				{
					this.OnscanChanging(value);
					this.SendPropertyChanging();
					this._scan = value;
					this.SendPropertyChanged("scan");
					this.OnscanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docs", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary docs
		{
			get
			{
				return this._docs;
			}
			set
			{
				if ((this._docs != value))
				{
					this.OndocsChanging(value);
					this.SendPropertyChanging();
					this._docs = value;
					this.SendPropertyChanged("docs");
					this.OndocsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userInRoles")]
	public partial class userInRoles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private int _RoleId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    #endregion
		
		public userInRoles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int NOT NULL")]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webpages_Membership")]
	public partial class webpages_Membership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _ConfirmationToken;
		
		private System.Nullable<bool> _IsConfirmed;
		
		private System.Nullable<System.DateTime> _LastPasswordFailureDate;
		
		private int _PasswordFailuresSinceLastSuccess;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _PasswordChangedDate;
		
		private string _PasswordSalt;
		
		private string _PasswordVerificationToken;
		
		private System.Nullable<System.DateTime> _PasswordVerificationTokenExpirationDate;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnConfirmationTokenChanging(string value);
    partial void OnConfirmationTokenChanged();
    partial void OnIsConfirmedChanging(System.Nullable<bool> value);
    partial void OnIsConfirmedChanged();
    partial void OnLastPasswordFailureDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPasswordFailureDateChanged();
    partial void OnPasswordFailuresSinceLastSuccessChanging(int value);
    partial void OnPasswordFailuresSinceLastSuccessChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordChangedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPasswordChangedDateChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnPasswordVerificationTokenChanging(string value);
    partial void OnPasswordVerificationTokenChanged();
    partial void OnPasswordVerificationTokenExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPasswordVerificationTokenExpirationDateChanged();
    #endregion
		
		public webpages_Membership()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmationToken", DbType="NVarChar(128)")]
		public string ConfirmationToken
		{
			get
			{
				return this._ConfirmationToken;
			}
			set
			{
				if ((this._ConfirmationToken != value))
				{
					this.OnConfirmationTokenChanging(value);
					this.SendPropertyChanging();
					this._ConfirmationToken = value;
					this.SendPropertyChanged("ConfirmationToken");
					this.OnConfirmationTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsConfirmed", DbType="Bit")]
		public System.Nullable<bool> IsConfirmed
		{
			get
			{
				return this._IsConfirmed;
			}
			set
			{
				if ((this._IsConfirmed != value))
				{
					this.OnIsConfirmedChanging(value);
					this.SendPropertyChanging();
					this._IsConfirmed = value;
					this.SendPropertyChanged("IsConfirmed");
					this.OnIsConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordFailureDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPasswordFailureDate
		{
			get
			{
				return this._LastPasswordFailureDate;
			}
			set
			{
				if ((this._LastPasswordFailureDate != value))
				{
					this.OnLastPasswordFailureDateChanging(value);
					this.SendPropertyChanging();
					this._LastPasswordFailureDate = value;
					this.SendPropertyChanged("LastPasswordFailureDate");
					this.OnLastPasswordFailureDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFailuresSinceLastSuccess", DbType="Int NOT NULL")]
		public int PasswordFailuresSinceLastSuccess
		{
			get
			{
				return this._PasswordFailuresSinceLastSuccess;
			}
			set
			{
				if ((this._PasswordFailuresSinceLastSuccess != value))
				{
					this.OnPasswordFailuresSinceLastSuccessChanging(value);
					this.SendPropertyChanging();
					this._PasswordFailuresSinceLastSuccess = value;
					this.SendPropertyChanged("PasswordFailuresSinceLastSuccess");
					this.OnPasswordFailuresSinceLastSuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordChangedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PasswordChangedDate
		{
			get
			{
				return this._PasswordChangedDate;
			}
			set
			{
				if ((this._PasswordChangedDate != value))
				{
					this.OnPasswordChangedDateChanging(value);
					this.SendPropertyChanging();
					this._PasswordChangedDate = value;
					this.SendPropertyChanged("PasswordChangedDate");
					this.OnPasswordChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordVerificationToken", DbType="NVarChar(128)")]
		public string PasswordVerificationToken
		{
			get
			{
				return this._PasswordVerificationToken;
			}
			set
			{
				if ((this._PasswordVerificationToken != value))
				{
					this.OnPasswordVerificationTokenChanging(value);
					this.SendPropertyChanging();
					this._PasswordVerificationToken = value;
					this.SendPropertyChanged("PasswordVerificationToken");
					this.OnPasswordVerificationTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordVerificationTokenExpirationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PasswordVerificationTokenExpirationDate
		{
			get
			{
				return this._PasswordVerificationTokenExpirationDate;
			}
			set
			{
				if ((this._PasswordVerificationTokenExpirationDate != value))
				{
					this.OnPasswordVerificationTokenExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._PasswordVerificationTokenExpirationDate = value;
					this.SendPropertyChanged("PasswordVerificationTokenExpirationDate");
					this.OnPasswordVerificationTokenExpirationDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webpages_OAuthMembership")]
	public partial class webpages_OAuthMembership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Provider;
		
		private string _ProviderUserId;
		
		private int _UserId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProviderChanging(string value);
    partial void OnProviderChanged();
    partial void OnProviderUserIdChanging(string value);
    partial void OnProviderUserIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    #endregion
		
		public webpages_OAuthMembership()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Provider
		{
			get
			{
				return this._Provider;
			}
			set
			{
				if ((this._Provider != value))
				{
					this.OnProviderChanging(value);
					this.SendPropertyChanging();
					this._Provider = value;
					this.SendPropertyChanged("Provider");
					this.OnProviderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderUserId", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProviderUserId
		{
			get
			{
				return this._ProviderUserId;
			}
			set
			{
				if ((this._ProviderUserId != value))
				{
					this.OnProviderUserIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderUserId = value;
					this.SendPropertyChanged("ProviderUserId");
					this.OnProviderUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webpages_Roles")]
	public partial class webpages_Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleId;
		
		private string _RoleName;
		
		private EntitySet<webpages_UsersInRoles> _webpages_UsersInRoles;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public webpages_Roles()
		{
			this._webpages_UsersInRoles = new EntitySet<webpages_UsersInRoles>(new Action<webpages_UsersInRoles>(this.attach_webpages_UsersInRoles), new Action<webpages_UsersInRoles>(this.detach_webpages_UsersInRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="webpages_Roles_webpages_UsersInRoles", Storage="_webpages_UsersInRoles", ThisKey="RoleId", OtherKey="RoleId")]
		public EntitySet<webpages_UsersInRoles> webpages_UsersInRoles
		{
			get
			{
				return this._webpages_UsersInRoles;
			}
			set
			{
				this._webpages_UsersInRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_webpages_UsersInRoles(webpages_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.webpages_Roles = this;
		}
		
		private void detach_webpages_UsersInRoles(webpages_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.webpages_Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webpages_UsersInRoles")]
	public partial class webpages_UsersInRoles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private int _RoleId;
		
		private EntityRef<webpages_Roles> _webpages_Roles;
		
		private EntityRef<UserProfile> _UserProfile;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    #endregion
		
		public webpages_UsersInRoles()
		{
			this._webpages_Roles = default(EntityRef<webpages_Roles>);
			this._UserProfile = default(EntityRef<UserProfile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._UserProfile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					if (this._webpages_Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="webpages_Roles_webpages_UsersInRoles", Storage="_webpages_Roles", ThisKey="RoleId", OtherKey="RoleId", IsForeignKey=true)]
		public webpages_Roles webpages_Roles
		{
			get
			{
				return this._webpages_Roles.Entity;
			}
			set
			{
				webpages_Roles previousValue = this._webpages_Roles.Entity;
				if (((previousValue != value) 
							|| (this._webpages_Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._webpages_Roles.Entity = null;
						previousValue.webpages_UsersInRoles.Remove(this);
					}
					this._webpages_Roles.Entity = value;
					if ((value != null))
					{
						value.webpages_UsersInRoles.Add(this);
						this._RoleId = value.RoleId;
					}
					else
					{
						this._RoleId = default(int);
					}
					this.SendPropertyChanged("webpages_Roles");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_webpages_UsersInRoles", Storage="_UserProfile", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public UserProfile UserProfile
		{
			get
			{
				return this._UserProfile.Entity;
			}
			set
			{
				UserProfile previousValue = this._UserProfile.Entity;
				if (((previousValue != value) 
							|| (this._UserProfile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserProfile.Entity = null;
						previousValue.webpages_UsersInRoles.Remove(this);
					}
					this._UserProfile.Entity = value;
					if ((value != null))
					{
						value.webpages_UsersInRoles.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("UserProfile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserProfile")]
	public partial class UserProfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private string _FIOShort;
		
		private EntitySet<webpages_UsersInRoles> _webpages_UsersInRoles;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFIOShortChanging(string value);
    partial void OnFIOShortChanged();
    #endregion
		
		public UserProfile()
		{
			this._webpages_UsersInRoles = new EntitySet<webpages_UsersInRoles>(new Action<webpages_UsersInRoles>(this.attach_webpages_UsersInRoles), new Action<webpages_UsersInRoles>(this.detach_webpages_UsersInRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(56) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIOShort", DbType="NVarChar(56)")]
		public string FIOShort
		{
			get
			{
				return this._FIOShort;
			}
			set
			{
				if ((this._FIOShort != value))
				{
					this.OnFIOShortChanging(value);
					this.SendPropertyChanging();
					this._FIOShort = value;
					this.SendPropertyChanged("FIOShort");
					this.OnFIOShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_webpages_UsersInRoles", Storage="_webpages_UsersInRoles", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<webpages_UsersInRoles> webpages_UsersInRoles
		{
			get
			{
				return this._webpages_UsersInRoles;
			}
			set
			{
				this._webpages_UsersInRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_webpages_UsersInRoles(webpages_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = this;
		}
		
		private void detach_webpages_UsersInRoles(webpages_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PredmetForUser")]
	public partial class PredmetForUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _spisokSemestr;
		
		private int _FIOUserID;
		
		private int _predmetId;
		
		private string _FIOShort;
		
		private string _predmetName;
		
		private string _potok;
		
		private string _kolvoGrupp;
		
		private string _kolvoPodGrupp;
		
		private string _kolvoStudent;
		
		private string _lekcii;
		
		private string _praktikaPlan;
		
		private string _praktikaVsego;
		
		private string _labPlan;
		
		private string _labVsego;
		
		private string _konsultTek;
		
		private string _konsultEkz;
		
		private string _exzamen;
		
		private string _zachet;
		
		private string _rykvoPract;
		
		private string _rykvoDJPpr;
		
		private string _chasSRS;
		
		private string _chasReit;
		
		private string _rykvoAspirant;
		
		private string _vsego;
		
		private string _assistent;
		
		private string _spisokYear;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnspisokSemestrChanging(string value);
    partial void OnspisokSemestrChanged();
    partial void OnFIOUserIDChanging(int value);
    partial void OnFIOUserIDChanged();
    partial void OnpredmetIdChanging(int value);
    partial void OnpredmetIdChanged();
    partial void OnFIOShortChanging(string value);
    partial void OnFIOShortChanged();
    partial void OnpredmetNameChanging(string value);
    partial void OnpredmetNameChanged();
    partial void OnpotokChanging(string value);
    partial void OnpotokChanged();
    partial void OnkolvoGruppChanging(string value);
    partial void OnkolvoGruppChanged();
    partial void OnkolvoPodGruppChanging(string value);
    partial void OnkolvoPodGruppChanged();
    partial void OnkolvoStudentChanging(string value);
    partial void OnkolvoStudentChanged();
    partial void OnlekciiChanging(string value);
    partial void OnlekciiChanged();
    partial void OnpraktikaPlanChanging(string value);
    partial void OnpraktikaPlanChanged();
    partial void OnpraktikaVsegoChanging(string value);
    partial void OnpraktikaVsegoChanged();
    partial void OnlabPlanChanging(string value);
    partial void OnlabPlanChanged();
    partial void OnlabVsegoChanging(string value);
    partial void OnlabVsegoChanged();
    partial void OnkonsultTekChanging(string value);
    partial void OnkonsultTekChanged();
    partial void OnkonsultEkzChanging(string value);
    partial void OnkonsultEkzChanged();
    partial void OnexzamenChanging(string value);
    partial void OnexzamenChanged();
    partial void OnzachetChanging(string value);
    partial void OnzachetChanged();
    partial void OnrykvoPractChanging(string value);
    partial void OnrykvoPractChanged();
    partial void OnrykvoDJPprChanging(string value);
    partial void OnrykvoDJPprChanged();
    partial void OnchasSRSChanging(string value);
    partial void OnchasSRSChanged();
    partial void OnchasReitChanging(string value);
    partial void OnchasReitChanged();
    partial void OnrykvoAspirantChanging(string value);
    partial void OnrykvoAspirantChanged();
    partial void OnvsegoChanging(string value);
    partial void OnvsegoChanged();
    partial void OnassistentChanging(string value);
    partial void OnassistentChanged();
    partial void OnspisokYearChanging(string value);
    partial void OnspisokYearChanged();
    #endregion
		
		public PredmetForUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spisokSemestr", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string spisokSemestr
		{
			get
			{
				return this._spisokSemestr;
			}
			set
			{
				if ((this._spisokSemestr != value))
				{
					this.OnspisokSemestrChanging(value);
					this.SendPropertyChanging();
					this._spisokSemestr = value;
					this.SendPropertyChanged("spisokSemestr");
					this.OnspisokSemestrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIOUserID", DbType="Int NOT NULL")]
		public int FIOUserID
		{
			get
			{
				return this._FIOUserID;
			}
			set
			{
				if ((this._FIOUserID != value))
				{
					this.OnFIOUserIDChanging(value);
					this.SendPropertyChanging();
					this._FIOUserID = value;
					this.SendPropertyChanged("FIOUserID");
					this.OnFIOUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_predmetId", DbType="Int NOT NULL")]
		public int predmetId
		{
			get
			{
				return this._predmetId;
			}
			set
			{
				if ((this._predmetId != value))
				{
					this.OnpredmetIdChanging(value);
					this.SendPropertyChanging();
					this._predmetId = value;
					this.SendPropertyChanged("predmetId");
					this.OnpredmetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIOShort", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FIOShort
		{
			get
			{
				return this._FIOShort;
			}
			set
			{
				if ((this._FIOShort != value))
				{
					this.OnFIOShortChanging(value);
					this.SendPropertyChanging();
					this._FIOShort = value;
					this.SendPropertyChanged("FIOShort");
					this.OnFIOShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_predmetName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string predmetName
		{
			get
			{
				return this._predmetName;
			}
			set
			{
				if ((this._predmetName != value))
				{
					this.OnpredmetNameChanging(value);
					this.SendPropertyChanging();
					this._predmetName = value;
					this.SendPropertyChanged("predmetName");
					this.OnpredmetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_potok", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string potok
		{
			get
			{
				return this._potok;
			}
			set
			{
				if ((this._potok != value))
				{
					this.OnpotokChanging(value);
					this.SendPropertyChanging();
					this._potok = value;
					this.SendPropertyChanged("potok");
					this.OnpotokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolvoGrupp", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kolvoGrupp
		{
			get
			{
				return this._kolvoGrupp;
			}
			set
			{
				if ((this._kolvoGrupp != value))
				{
					this.OnkolvoGruppChanging(value);
					this.SendPropertyChanging();
					this._kolvoGrupp = value;
					this.SendPropertyChanged("kolvoGrupp");
					this.OnkolvoGruppChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolvoPodGrupp", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kolvoPodGrupp
		{
			get
			{
				return this._kolvoPodGrupp;
			}
			set
			{
				if ((this._kolvoPodGrupp != value))
				{
					this.OnkolvoPodGruppChanging(value);
					this.SendPropertyChanging();
					this._kolvoPodGrupp = value;
					this.SendPropertyChanged("kolvoPodGrupp");
					this.OnkolvoPodGruppChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolvoStudent", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kolvoStudent
		{
			get
			{
				return this._kolvoStudent;
			}
			set
			{
				if ((this._kolvoStudent != value))
				{
					this.OnkolvoStudentChanging(value);
					this.SendPropertyChanging();
					this._kolvoStudent = value;
					this.SendPropertyChanged("kolvoStudent");
					this.OnkolvoStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lekcii", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string lekcii
		{
			get
			{
				return this._lekcii;
			}
			set
			{
				if ((this._lekcii != value))
				{
					this.OnlekciiChanging(value);
					this.SendPropertyChanging();
					this._lekcii = value;
					this.SendPropertyChanged("lekcii");
					this.OnlekciiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_praktikaPlan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string praktikaPlan
		{
			get
			{
				return this._praktikaPlan;
			}
			set
			{
				if ((this._praktikaPlan != value))
				{
					this.OnpraktikaPlanChanging(value);
					this.SendPropertyChanging();
					this._praktikaPlan = value;
					this.SendPropertyChanged("praktikaPlan");
					this.OnpraktikaPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_praktikaVsego", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string praktikaVsego
		{
			get
			{
				return this._praktikaVsego;
			}
			set
			{
				if ((this._praktikaVsego != value))
				{
					this.OnpraktikaVsegoChanging(value);
					this.SendPropertyChanging();
					this._praktikaVsego = value;
					this.SendPropertyChanged("praktikaVsego");
					this.OnpraktikaVsegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labPlan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string labPlan
		{
			get
			{
				return this._labPlan;
			}
			set
			{
				if ((this._labPlan != value))
				{
					this.OnlabPlanChanging(value);
					this.SendPropertyChanging();
					this._labPlan = value;
					this.SendPropertyChanged("labPlan");
					this.OnlabPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labVsego", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string labVsego
		{
			get
			{
				return this._labVsego;
			}
			set
			{
				if ((this._labVsego != value))
				{
					this.OnlabVsegoChanging(value);
					this.SendPropertyChanging();
					this._labVsego = value;
					this.SendPropertyChanged("labVsego");
					this.OnlabVsegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konsultTek", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string konsultTek
		{
			get
			{
				return this._konsultTek;
			}
			set
			{
				if ((this._konsultTek != value))
				{
					this.OnkonsultTekChanging(value);
					this.SendPropertyChanging();
					this._konsultTek = value;
					this.SendPropertyChanged("konsultTek");
					this.OnkonsultTekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konsultEkz", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string konsultEkz
		{
			get
			{
				return this._konsultEkz;
			}
			set
			{
				if ((this._konsultEkz != value))
				{
					this.OnkonsultEkzChanging(value);
					this.SendPropertyChanging();
					this._konsultEkz = value;
					this.SendPropertyChanged("konsultEkz");
					this.OnkonsultEkzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exzamen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string exzamen
		{
			get
			{
				return this._exzamen;
			}
			set
			{
				if ((this._exzamen != value))
				{
					this.OnexzamenChanging(value);
					this.SendPropertyChanging();
					this._exzamen = value;
					this.SendPropertyChanged("exzamen");
					this.OnexzamenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zachet", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string zachet
		{
			get
			{
				return this._zachet;
			}
			set
			{
				if ((this._zachet != value))
				{
					this.OnzachetChanging(value);
					this.SendPropertyChanging();
					this._zachet = value;
					this.SendPropertyChanged("zachet");
					this.OnzachetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rykvoPract", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string rykvoPract
		{
			get
			{
				return this._rykvoPract;
			}
			set
			{
				if ((this._rykvoPract != value))
				{
					this.OnrykvoPractChanging(value);
					this.SendPropertyChanging();
					this._rykvoPract = value;
					this.SendPropertyChanged("rykvoPract");
					this.OnrykvoPractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rykvoDJPpr", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string rykvoDJPpr
		{
			get
			{
				return this._rykvoDJPpr;
			}
			set
			{
				if ((this._rykvoDJPpr != value))
				{
					this.OnrykvoDJPprChanging(value);
					this.SendPropertyChanging();
					this._rykvoDJPpr = value;
					this.SendPropertyChanged("rykvoDJPpr");
					this.OnrykvoDJPprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chasSRS", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string chasSRS
		{
			get
			{
				return this._chasSRS;
			}
			set
			{
				if ((this._chasSRS != value))
				{
					this.OnchasSRSChanging(value);
					this.SendPropertyChanging();
					this._chasSRS = value;
					this.SendPropertyChanged("chasSRS");
					this.OnchasSRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chasReit", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string chasReit
		{
			get
			{
				return this._chasReit;
			}
			set
			{
				if ((this._chasReit != value))
				{
					this.OnchasReitChanging(value);
					this.SendPropertyChanging();
					this._chasReit = value;
					this.SendPropertyChanged("chasReit");
					this.OnchasReitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rykvoAspirant", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string rykvoAspirant
		{
			get
			{
				return this._rykvoAspirant;
			}
			set
			{
				if ((this._rykvoAspirant != value))
				{
					this.OnrykvoAspirantChanging(value);
					this.SendPropertyChanging();
					this._rykvoAspirant = value;
					this.SendPropertyChanged("rykvoAspirant");
					this.OnrykvoAspirantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vsego", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string vsego
		{
			get
			{
				return this._vsego;
			}
			set
			{
				if ((this._vsego != value))
				{
					this.OnvsegoChanging(value);
					this.SendPropertyChanging();
					this._vsego = value;
					this.SendPropertyChanged("vsego");
					this.OnvsegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assistent", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string assistent
		{
			get
			{
				return this._assistent;
			}
			set
			{
				if ((this._assistent != value))
				{
					this.OnassistentChanging(value);
					this.SendPropertyChanging();
					this._assistent = value;
					this.SendPropertyChanged("assistent");
					this.OnassistentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spisokYear", DbType="NVarChar(MAX)")]
		public string spisokYear
		{
			get
			{
				return this._spisokYear;
			}
			set
			{
				if ((this._spisokYear != value))
				{
					this.OnspisokYearChanging(value);
					this.SendPropertyChanging();
					this._spisokYear = value;
					this.SendPropertyChanged("spisokYear");
					this.OnspisokYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
